### ISSUE TITLE
Toggle class .open bei Navigationen mit mehr als 2 Leveln

### ISSUE THREAD

**Issue by Shoekrates** [heimseiten/contao-mobile-navigation-bundle#1]
Hi! Danke für die Erweiterung, der Ansatz ohne jQuery gefällt mir.

Ich habe einen kleinen Bug entdeckt:
Zum Nachstellen:

- Die Hauptnavigation hat mind. drei Ebenen.
- Level_2 wird geöffnet und bekommt dadurch die Klasse .open
- Level_3 wird geöffnet und bekommt dadurch ebenfalls Klasse .open
- schließt man dann direkt Level_2, bleibt die Klasse .open bei Level_3 erhalten und der vertikale Raum für Level_3 bleibt erhalten. Dadurch sind die Navigationspunkte von Level_2 auseinandergezogen.

Das JS bräuchte also beim Toggle der Klasse .open noch eine Abfrage, ob Kindelemente auch eine Klasse .open haben, um diese dann auch zu togglen.

**Comment by heimseiten** [comment]
Danke. Wurde in Version 3.0.6 behoben. Allerdings mit CSS, da so die Untermenüs ihren Status behalten können.

**Comment by Shoekrates** [comment]
Vielen Dank für die superschnelle Reaktion. Funktioniert!
